### ISSUE TITLE
Hardware Check fails on Linux

### ISSUE THREAD

**Issue by LhymeFruit** [BullyWiiPlaza/Black-Ops-II-WiiU-Mod-Injector#1]
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:100)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302)
	at java.base/java.util.Objects.checkIndex(Objects.java:359)
	at java.base/java.util.ArrayList.get(ArrayList.java:427)
	at rH.M(vja:111)
	at fH.G(taa:113)
	at fH.M(taa:14)
	at fH.a(taa:245)
	at pG.l(to:289)
	at pG.b(to:681)
	at pG.L(to:236)
	at pG.M(to:125)
	at pG.m(to:101)
	at pG.M(to:1984)
	at BlackOpsIIWiiUModInjectorClient.main(sea:351)

**Comment by LhymeFruit** [comment]
i just want to use the unlock everything

**Comment by BullyWiiPlaza** [comment]
Hi, it looks like you're running Linux. If you have access to a Windows machine, please try that. It mostly likely works fine on Windows even though I did develop working Linux support. I'm not entirely sure why the Linux hardware check for the license key fails but I probably won't fix this issue soon so please consider using Windows.

**Comment by LhymeFruit** [comment]
> Hi, it looks like you're running Linux. If you have access to a Windows machine, please try that. It mostly likely works fine on Windows even though I did develop working Linux support. I'm not entirely sure why the Linux hardware check for the license key fails but I probably won't fix this issue soon so please consider using Windows.

seriously? why just this program, jars are supposed to be universal

**Comment by BullyWiiPlaza** [comment]
They are universal, there is just a Linux specific bug in the platform dependent code which checks for the license key to determine your access level to the application.

**Comment by LhymeFruit** [comment]
why dont you shove that paywall up your ass dickhead

**Comment by BullyWiiPlaza** [comment]
Your attitude is why, don't go through life expecting others owe you when you just want to be a leecher, kiddo. :)

**Comment by LhymeFruit** [comment]
> Your attitude is why, don't go through life expecting others owe you when you just want to be a leecher, kiddo. :)

stfu im not the one trying to sell hacks for a dead game

**Comment by BullyWiiPlaza** [comment]
> > Your attitude is why, don't go through life expecting others owe you when you just want to be a leecher, kiddo. :)
> 
> stfu im not the one trying to sell hacks for a dead game

So what, you play and probably spend money on a children's block game (Minecraft). Imagine doing this in 2022. 🤷‍♂️

**Comment by LhymeFruit** [comment]
> > > Your attitude is why, don't go through life expecting others owe you when you just want to be a leecher, kiddo. :)
> > 
> > 
> > stfu im not the one trying to sell hacks for a dead game
> 
> So what, you play and probably spend money on a children's block game (Minecraft). Imagine doing this in 2022. man_shrugging

bruh you litterally made an injector for this childrens block game XD

**Comment by BullyWiiPlaza** [comment]
lol, you're wrong again. Last reply. I maybe worked on the Minecraft injector for 1 - 2 days in total (!) because it was mainly developed by SlothWiiPlaza. Can you tell the difference in names? I don't really play Minecraft. So that's all.

**Comment by LhymeFruit** [comment]
> lol, you're wrong again. Last reply. I maybe worked on the Minecraft injector for 1 - 2 days in total (!) because it was mainly developed by SlothWiiPlaza. Can you tell the difference in names? I don't really play Minecraft. So that's all.

maybe? bro really forgot what he did
